/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MayMax (https://sketchfab.com/MayMax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-chrome-dino-duck-walking-c918a3a7fdd44a21875b13d793c57dd6
Title: 3D Chrome Dino Duck-Walking
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dino(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/dino.glb')
  const { actions } = useAnimations(animations, group)

  // useEffect(() => {
  //   actions["Walking"].play( 10 );
  //   return () => actions["Walking"].fadeOut(0.5);
  // }, []);

  return (
    <group ref={group} {...props} dispose={null} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="sketchfabtimeframe">
            <group name="Object_2" scale={0}>
              <group name="frame_3">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.palette_0}
                />
              </group>
            </group>
            <group name="Object_5" scale={0}>
              <group name="frame_2">
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.palette}
                />
              </group>
            </group>
            <group name="Object_8" scale={0}>
              <group name="frame_3_1">
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.palette_0}
                />
              </group>
            </group>
            <group name="Object_11">
              <group name="frame_2_1">
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.palette}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dino.glb')