/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MayMax (https://sketchfab.com/MayMax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-cactus-1x2-2e015aa2ea5349d689353a3fad894faf
Title: Voxel Cactus 1x2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SingleCactus(props) {
  const { nodes, materials } = useGLTF('/cactusx1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.palette}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/cactusx1.glb')